/**
 * `get_ui_blocks` — returns ready-made page sections (official shadcn/ui blocks
 * plus blocks authored on the kit's layout primitives) as one JSX snippet for
 * `public/app.jsx`, with the imports of all selected blocks merged. Runs in the
 * ThinkAgent DO; the catalog is generated by scripts/think-ui-kit/build.sh.
 */
import { tool, type Tool } from 'ai';
import { z } from 'zod';
import { UI_BLOCKS, type UiBlock } from './ui-kit/catalog';

const BLOCK_NAMES = UI_BLOCKS.map((block) => block.name) as [string, ...string[]];

const DESCRIPTION = [
	'Get ready-made, responsive page sections built from the scaffold_ui_kit components and layout primitives, as one JSX snippet to paste into public/app.jsx. Start every page from these instead of inventing layout and spacing; then replace the placeholder text, data and images with the real content and compose the entries in your App.',
	'',
	'Request every block the page needs in one call so imports are merged. Blocks:',
	...(['marketing', 'app', 'auth'] as const).flatMap((category) => [
		`${category}:`,
		...UI_BLOCKS.filter((block) => block.category === category).map((block) => `- ${block.name}: ${block.description}`),
	]),
].join('\n');

function mergeImports(blocks: readonly UiBlock[]): string {
	const react = new Set<string>();
	const lucide = new Set<string>();
	const motion = new Set<string>();
	const kit = new Set<string>();
	let reactNamespace = false;
	for (const block of blocks) {
		reactNamespace ||= block.imports.reactNamespace;
		block.imports.react.forEach((name) => react.add(name));
		block.imports.lucide.forEach((name) => lucide.add(name));
		block.imports.motion.forEach((name) => motion.add(name));
		block.imports.kit.forEach((name) => kit.add(name));
	}
	// toast() only shows anything once <Toaster /> is rendered at the app root.
	if (kit.has('toast')) kit.add('Toaster');
	const lines: string[] = [];
	if (reactNamespace) lines.push('import * as React from "react";');
	if (react.size) lines.push(`import { ${[...react].sort().join(', ')} } from "react";`);
	if (lucide.size) lines.push(`import { ${[...lucide].sort().join(', ')} } from "lucide-react";`);
	if (motion.size) lines.push(`import { ${[...motion].sort().join(', ')} } from "motion/react";`);
	if (kit.size) lines.push(`import { ${[...kit].sort().join(', ')} } from "./vendor/ui-kit.js";`);
	return lines.join('\n');
}

function findClashes(blocks: readonly UiBlock[]): string[] {
	const owners = new Map<string, string[]>();
	for (const block of blocks) {
		for (const name of block.declarations) owners.set(name, [...(owners.get(name) ?? []), block.name]);
	}
	return [...owners].filter(([, names]) => names.length > 1).map(([name, names]) => `${name} (${names.join(', ')})`);
}

export function createGetUiBlocksTool(): Tool {
	return tool({
		description: DESCRIPTION,
		inputSchema: z.object({
			names: z.array(z.enum(BLOCK_NAMES)).min(1).describe('Blocks to combine, in page order.'),
		}),
		execute: async (args: { names: string[] }) => {
			const names = [...new Set(args.names)];
			const blocks = names.map((name) => UI_BLOCKS.find((block) => block.name === name)!);
			const clashes = findClashes(blocks);
			if (clashes.length) {
				return JSON.stringify({
					ok: false,
					error: `These blocks declare the same top-level names and are alternatives to each other: ${clashes.join('; ')}. Request only one of them.`,
				});
			}
			return JSON.stringify({
				ok: true,
				entries: blocks.map((block) => ({ block: block.name, render: block.entry, notes: block.notes || undefined })),
				code: `${mergeImports(blocks)}\n\n${blocks.map((block) => `// ── ${block.name} ──\n${block.body}`).join('\n')}`,
				next_steps: [
					'Paste `code` into public/app.jsx, merging its import lines with any you already have (a name imported twice is a syntax error).',
					'Render the entries in page order inside your App, e.g. function App() { return (<><MarketingHeader /><main><HeroSplit /></main><SiteFooter /><Toaster /></>); }',
					'Replace every placeholder (headings, copy, data arrays, "Brand", images) with real content for this brief. Keep the structure, layout primitives and token classes; adjust content, not spacing.',
					...(blocks.some((block) => block.imports.motion.length > 0)
						? [
								'These blocks animate with "motion/react". scaffold_ui_kit maps it in the import map of public/index.html; if the browser cannot resolve "motion/react", call scaffold_ui_kit again. Keep the animations as written: they already respect reduced motion.',
							]
						: []),
				],
			});
		},
	});
}
