#!/usr/bin/env bash
# Builds the precompiled shadcn/ui component kit that ThinkAgent vendors into
# generated React apps (see worker/agents/think/scaffold-ui-kit-tool.ts).
#
# Why precompiled: ThinkAgent's preview pipeline (@cloudflare/worker-bundler)
# ships `public/` assets byte-for-byte, with no JSX transform and no
# Tailwind/PostCSS build step. The real shadcn/ui + Radix + Tailwind source
# can't run in that environment as-is, so we compile it once, offline, here,
# and commit the plain ESM JS + static CSS output for the agent to vendor
# verbatim into any new app.
#
# Source of truth for component source: the real shadcn CLI output already
# checked in at templates/build/vite-cf-DO-v2-runner/src/components/ui. Re-run
# this script after regenerating/updating that template's components.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

TEMPLATE_SRC="../../templates/build/vite-cf-DO-v2-runner/src"
OUT_DIR="../../worker/agents/think/ui-kit"
GEN_DIR=".gen"

# Curated subset of the template's shadcn/ui components: covers nav, forms,
# overlays, and feedback without pulling in components that need extra
# integration (react-hook-form, react-day-picker, recharts, cmdk, vaul, etc).
COMPONENTS=(
  accordion alert alert-dialog aspect-ratio avatar badge breadcrumb button
  card checkbox collapsible dialog dropdown-menu hover-card input label
  navigation-menu pagination popover progress radio-group scroll-area select
  separator sheet sidebar skeleton slider sonner switch table tabs textarea
  tooltip
)

rm -rf "$GEN_DIR"
mkdir -p "$GEN_DIR/src/components/ui" "$GEN_DIR/src/components/layout" "$GEN_DIR/src/lib" "$GEN_DIR/src/hooks"

for c in "${COMPONENTS[@]}"; do
  cp "$TEMPLATE_SRC/components/ui/$c.tsx" "$GEN_DIR/src/components/ui/$c.tsx"
done
cp "$TEMPLATE_SRC/lib/utils.ts" "$GEN_DIR/src/lib/utils.ts"
cp "$TEMPLATE_SRC/hooks/use-mobile.tsx" "$GEN_DIR/src/hooks/use-mobile.tsx"
# sonner.tsx override: drops the `next-themes` dependency (ThemeProvider-free)
# so the kit has no required context providers.
cp overrides/sonner.tsx "$GEN_DIR/src/components/ui/sonner.tsx"
# Layout primitives (Container, Section, Stack, Grid, ...) with one spacing scale.
cp layout/layout.tsx "$GEN_DIR/src/components/layout/layout.tsx"

{
  for c in "${COMPONENTS[@]}"; do
    echo "export * from \"./src/components/ui/$c\";"
  done
  echo "export * from \"./src/components/layout/layout\";"
  echo "export { cn } from \"./src/lib/utils\";"
} > "$GEN_DIR/entry.ts"

cat > "$GEN_DIR/tsconfig.json" <<'EOF'
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["./src/*"] },
    "jsx": "react-jsx"
  }
}
EOF
ln -sf ../node_modules "$GEN_DIR/node_modules"

BANNER="/* Precompiled shadcn/ui + Radix UI (MIT) component kit. Generated by scripts/think-ui-kit/build.sh — do not hand-edit. */"

mkdir -p "$OUT_DIR"

npx esbuild "$GEN_DIR/entry.ts" \
  --bundle \
  --format=esm \
  --platform=browser \
  --target=es2020 \
  --jsx=automatic \
  --external:react \
  --external:react-dom \
  --external:react/jsx-runtime \
  --minify \
  --banner:js="$BANNER" \
  --outfile="$OUT_DIR/ui-kit.js"

# Theme presets ([data-theme="..."]) come from the vendored shadcn themes.
node prepare-themes.mjs "$GEN_DIR/themes.css"
cat input.css "$GEN_DIR/themes.css" > "$GEN_DIR/input.css"

# Output as .css.js, not .css: under @cloudflare/vitest-pool-workers, a plain
# `.css?raw` import silently resolves to an empty string (verified: neither
# the root project's Tailwind v4 plugin nor any wrangler.jsonc rule explains
# it — `.css` is just special-cased to empty by the test pool). `.txt?raw`
# fails outright ("no such module") under the same pool. Only `.md?raw` and
# `.js?raw` were verified to resolve real content in both the test pool and
# real `wrangler deploy`, so the compiled CSS is stored with a `.js` extension
# purely to piggyback on that working raw-text path. The file written into
# the generated app is still named ui-kit.css (see scaffold-ui-kit-tool.ts) —
# only this in-repo copy needs the extra extension.

npx tailwindcss \
  -i "$GEN_DIR/input.css" \
  -o "$OUT_DIR/ui-kit.css.js" \
  --config tailwind.config.cjs \
  --minify

echo "Built $OUT_DIR/ui-kit.js and $OUT_DIR/ui-kit.css.js"

# Blocks, export list, theme names and the runtime Tailwind config, generated
# from the kit just built so the tool can never drift from it.
node build-catalog.mjs
